param(
    [Parameter(Mandatory=$true)]
    [string]$RepoUrl,

    [string]$Branch = "main",

    [switch]$DryRun,

    [switch]$IncludeData
)

$ErrorActionPreference = "Stop"

function Say($Message) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$ts] $Message"
}

$ProjectRoot = "D:\Good Measure\MentalWellbeingbyGeography"
if (!(Test-Path $ProjectRoot)) {
    throw "Project root not found: $ProjectRoot"
}
Set-Location $ProjectRoot

Say "Preparing GitHub push for MentalWellbeingByGeography"
Say "Project root: $ProjectRoot"
Say "Repo URL: $RepoUrl"
Say "Branch: $Branch"
if ($DryRun) { Say "Mode: DRY RUN" } else { Say "Mode: APPLY" }
Say "Include data: $IncludeData"

# Check git exists
$gitVersion = & git --version
if ($LASTEXITCODE -ne 0) { throw "Git is not available on PATH." }
Say $gitVersion

# Plain .gitignore text. No helper function, no validated string-array params.
$GitIgnoreLines = @(
    "# MentalWellbeingByGeography safe GitHub exclusions",
    "# Generated by 36_push_mentalwellbeingbygeography_to_github.ps1",
    "",
    "# Python / editor / OS",
    "__pycache__/",
    "*.pyc",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".venv/",
    "venv/",
    "env/",
    ".ipynb_checkpoints/",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    ".vscode/",
    ".idea/",
    "",
    "# Data and large artefacts excluded by default",
    "data/raw/",
    "data/processed/",
    "data/interim/",
    "data/external/",
    "data/archive/",
    "data/_archive/",
    "data/_quarantine/",
    "",
    "# Outputs",
    "outputs/logs/",
    "outputs/archive/",
    "outputs/figures/",
    "outputs/tables/",
    "",
    "# Large/binary formats",
    "*.parquet",
    "*.zip",
    "*.7z",
    "*.rar",
    "*.xlsx",
    "*.xls",
    "*.xlsm",
    "*.pdf",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.sqlite",
    "*.db",
    "",
    "# Keep code/docs/audit CSVs trackable unless under ignored folders above"
)

if ($IncludeData) {
    $GitIgnoreLines = $GitIgnoreLines | Where-Object { $_ -notin @("data/raw/", "data/processed/", "data/interim/", "data/external/") }
    Say "WARNING: IncludeData enabled. Data folders will not be excluded by .gitignore, but large binary patterns still apply."
}

$GitIgnorePath = Join-Path $ProjectRoot ".gitignore"
$ReadmePath = Join-Path $ProjectRoot "README.md"
$AuditDir = Join-Path $ProjectRoot "outputs\audits"
if (!(Test-Path $AuditDir)) {
    if ($DryRun) {
        Say "Would create audit directory: $AuditDir"
    } else {
        New-Item -ItemType Directory -Force $AuditDir | Out-Null
    }
}

if ($DryRun) {
    Say "Would initialise Git repository if needed."
    Say "Would write .gitignore: $GitIgnorePath"
    if (!(Test-Path $ReadmePath)) { Say "Would write README.md: $ReadmePath" }
    Say "Would set branch to: $Branch"
    Say "Would set remote origin to: $RepoUrl"
    Say "Would stage: .gitignore, README.md, scripts, docs, outputs/audits"
    Say "Would commit and push to origin/$Branch"

    $PlanPath = Join-Path $AuditDir ("github_push_dry_run_plan_v02_" + (Get-Date -Format "yyyyMMdd_HHmmss") + ".txt")
    $PlanLines = @(
        "MentalWellbeingByGeography GitHub push dry-run plan",
        "ProjectRoot=$ProjectRoot",
        "RepoUrl=$RepoUrl",
        "Branch=$Branch",
        "IncludeData=$IncludeData",
        "",
        "Files/directories that would be staged:",
        "  .gitignore",
        "  README.md",
        "  scripts/",
        "  docs/",
        "  outputs/audits/",
        "",
        "Ignored by default:",
        "  data/raw/",
        "  data/processed/",
        "  outputs/logs/",
        "  outputs/archive/",
        "  large binary formats"
    )
    Set-Content -Path $PlanPath -Value $PlanLines -Encoding UTF8
    Say "Dry-run plan written: $PlanPath"
    exit 0
}

# Apply mode starts here.
if (!(Test-Path (Join-Path $ProjectRoot ".git"))) {
    Say "Initialising Git repository"
    & git init
    if ($LASTEXITCODE -ne 0) { throw "git init failed" }
} else {
    Say "Existing Git repository found"
}

Say "Writing .gitignore"
Set-Content -Path $GitIgnorePath -Value $GitIgnoreLines -Encoding UTF8

if (!(Test-Path $ReadmePath)) {
    Say "Writing README.md"
    $ReadmeLines = @(
        "# MentalWellbeingByGeography",
        "",
        "A Good Measure data and evidence project building a geography-scoped predictor universe for mental wellbeing, service context and community need analysis in Australia.",
        "",
        "This repository tracks project code, documentation and lightweight audit artefacts. Raw data, processed data, logs, archives and large binary files are excluded by default.",
        "",
        "## Project structure",
        "",
        "- `scripts/` project acquisition, integration, audit and modelling scripts",
        "- `docs/` methodology notes, source registers and data dictionaries",
        "- `outputs/audits/` lightweight audit outputs used to document processing decisions",
        "",
        "## Data note",
        "",
        "Raw and processed datasets are not committed to this repository. Rebuilds should use the documented acquisition and processing scripts."
    )
    Set-Content -Path $ReadmePath -Value $ReadmeLines -Encoding UTF8
} else {
    Say "README.md already exists; leaving it unchanged"
}

Say "Setting branch"
& git branch -M $Branch
if ($LASTEXITCODE -ne 0) { throw "git branch failed" }

Say "Configuring remote origin"
$existingRemote = (& git remote get-url origin 2>$null)
if ($LASTEXITCODE -eq 0 -and $existingRemote) {
    & git remote set-url origin $RepoUrl
    if ($LASTEXITCODE -ne 0) { throw "git remote set-url failed" }
} else {
    & git remote add origin $RepoUrl
    if ($LASTEXITCODE -ne 0) { throw "git remote add failed" }
}

Say "Staging repository files"
& git add .gitignore README.md scripts docs outputs/audits
if ($LASTEXITCODE -ne 0) { throw "git add failed" }

$StatusPath = Join-Path $AuditDir ("github_push_status_before_commit_v02_" + (Get-Date -Format "yyyyMMdd_HHmmss") + ".txt")
& git status --short | Out-File -FilePath $StatusPath -Encoding UTF8
Say "Git status written: $StatusPath"

$staged = & git diff --cached --name-only
if (($staged | Measure-Object).Count -eq 0) {
    Say "No staged changes to commit."
} else {
    $CommitMessage = "Initial MentalWellbeingByGeography project commit"
    Say "Committing staged changes"
    & git commit -m $CommitMessage
    if ($LASTEXITCODE -ne 0) { throw "git commit failed" }
}

Say "Pushing to GitHub"
& git push -u origin $Branch
if ($LASTEXITCODE -ne 0) { throw "git push failed. Check the repository URL, GitHub authentication, and whether the remote repo exists." }

Say "GitHub push complete."
