from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"D:\Good Measure\MentalWellbeingbyGeography")

OUTPUT_PATH = PROJECT_ROOT / "docs" / "source_registers" / "source_acquisition_register.csv"

COLUMNS = [
    "source_id",
    "source_name",
    "publisher",
    "dataset_or_product_name",
    "source_url_or_access_path",
    "predictor_domain",
    "candidate_variables",
    "reference_period",
    "desired_reference_period",
    "temporal_alignment_status",
    "native_geography_level",
    "required_join_geography",
    "bridge_or_correspondence_required",
    "proposed_join_method",
    "weight_or_allocation_method",
    "suppression_or_missingness_rule",
    "candidate_predictor_status",
    "outcome_overlap_risk",
    "target_leakage_risk",
    "interpretation_limit",
    "download_status",
    "integration_status",
    "validation_status",
    "notes",
]

ROWS = [
    {
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "publisher": "ABS",
        "dataset_or_product_name": "ASGS Edition 3 SA2 geography",
        "source_url_or_access_path": "",
        "predictor_domain": "geography",
        "candidate_variables": "SA2 code; SA2 name; SA3 code; SA3 name; state/territory code; state/territory name",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct spine",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "interpretation_limit": "Geographic spine only.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "First build component.",
    },
    {
        "source_id": "SRC002",
        "source_name": "NSMHW modelled mental-health prevalence",
        "publisher": "ABS",
        "dataset_or_product_name": "National Study of Mental Health and Wellbeing 2020-2022",
        "source_url_or_access_path": "",
        "predictor_domain": "outcome",
        "candidate_variables": "nsmhw_any_12m_disorder_estimated_pct; nsmhw_severe_12m_disorder_estimated_pct",
        "reference_period": "2020-2022",
        "desired_reference_period": "2020-2022",
        "temporal_alignment_status": "aligned if SA2 estimates available",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join by SA2",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "ABS reliability/suppression rules required",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "high",
        "target_leakage_risk": "high",
        "interpretation_limit": "ABS modelled estimates, not observed counts.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Primary and secondary outcome source.",
    },
    {
        "source_id": "SRC003",
        "source_name": "Census 2021 SA2 predictors",
        "publisher": "ABS",
        "dataset_or_product_name": "Census 2021 data packs or TableBuilder exports",
        "source_url_or_access_path": "",
        "predictor_domain": "demographic; socioeconomic; housing; language; ancestry; disability; caring",
        "candidate_variables": "Census demographic; socioeconomic; language; ancestry; country of birth; housing; disability; caring variables",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join by SA2",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "Census non-response and small-cell handling required",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "high",
        "target_leakage_risk": "medium",
        "interpretation_limit": "May overlap with ABS small-area model covariates.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Core SA2 predictor source.",
    },
    {
        "source_id": "SRC004",
        "source_name": "SEIFA 2021",
        "publisher": "ABS",
        "dataset_or_product_name": "Socio-Economic Indexes for Areas 2021",
        "source_url_or_access_path": "",
        "predictor_domain": "socioeconomic disadvantage",
        "candidate_variables": "IRSD; IRSAD; IER; IEO; rankings; deciles; percentiles",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join by SA2",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "ABS availability rules",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "high",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Composite socioeconomic indexes may overlap with outcome model inputs.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Core disadvantage domain.",
    },
    {
        "source_id": "SRC005",
        "source_name": "ASGS Remoteness 2021",
        "publisher": "ABS",
        "dataset_or_product_name": "ASGS Remoteness Structure",
        "source_url_or_access_path": "",
        "predictor_domain": "remoteness",
        "candidate_variables": "Remoteness Area category; ordinal remoteness representation if defensible",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join or correspondence",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "low",
        "interpretation_limit": "Area remoteness context, not causal effect.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Core geography context.",
    },
    {
        "source_id": "SRC006",
        "source_name": "AIHW Regional Profiles mental-health service activity",
        "publisher": "AIHW",
        "dataset_or_product_name": "Regional profiles of mental health service activity",
        "source_url_or_access_path": "",
        "predictor_domain": "mental health service activity",
        "candidate_variables": "Medicare; PBS; ED; hospital; admitted patient; community mental health service activity rates",
        "reference_period": "2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check release tables",
        "native_geography_level": "SA3 and PHN",
        "required_join_geography": "SA3",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "join SA3 indicators to SA2 through sa3_code_2021",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "suppression and publication flags required",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Service activity, not access adequacy or community-managed psychosocial support availability.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Higher-level service context.",
    },
    {
        "source_id": "SRC007",
        "source_name": "DSS payments by SA2",
        "publisher": "DSS",
        "dataset_or_product_name": "DSS payments by Statistical Area 2",
        "source_url_or_access_path": "",
        "predictor_domain": "social security",
        "candidate_variables": "JobSeeker; Youth Allowance; Disability Support Pension; Carer Payment; Parenting Payment; Age Pension; Family Tax Benefit; Commonwealth Rent Assistance",
        "reference_period": "2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check quarterly period",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join by SA2",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "suppression and small-cell rules required",
        "candidate_predictor_status": "integrate_after_period_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Area-level social-security context only.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "High-priority social context.",
    },
    {
        "source_id": "SRC008",
        "source_name": "ABS Personal Income",
        "publisher": "ABS",
        "dataset_or_product_name": "Personal Income in Australia or Data by Region",
        "source_url_or_access_path": "",
        "predictor_domain": "income",
        "candidate_variables": "median income; mean income; income earners; income source measures",
        "reference_period": "2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check geography and period",
        "native_geography_level": "SA2 or SA3",
        "required_join_geography": "SA2 or SA3",
        "bridge_or_correspondence_required": "maybe",
        "proposed_join_method": "direct or SA3 repeat depending native geography",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "ABS confidentiality rules",
        "candidate_predictor_status": "integrate_after_period_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Income context may overlap with SEIFA and Census income.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Collinearity expected.",
    },
    {
        "source_id": "SRC009",
        "source_name": "ABS Jobs in Australia",
        "publisher": "ABS",
        "dataset_or_product_name": "Jobs in Australia",
        "source_url_or_access_path": "",
        "predictor_domain": "labour market",
        "candidate_variables": "jobs; job holders; industry; employment structure",
        "reference_period": "2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check geography and period",
        "native_geography_level": "SA2",
        "required_join_geography": "SA2",
        "bridge_or_correspondence_required": "no",
        "proposed_join_method": "direct join by SA2",
        "weight_or_allocation_method": "not applicable",
        "suppression_or_missingness_rule": "ABS confidentiality rules",
        "candidate_predictor_status": "integrate_after_period_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Labour-market context, not individual employment risk.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Potential high collinearity with Census labour variables.",
    },
    {
        "source_id": "SRC010",
        "source_name": "NDIS participant and market data",
        "publisher": "NDIA",
        "dataset_or_product_name": "NDIS quarterly reports and data downloads",
        "source_url_or_access_path": "",
        "predictor_domain": "disability; psychosocial support",
        "candidate_variables": "participant counts; psychosocial indicators; plan utilisation; provider market indicators",
        "reference_period": "2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check geography and psychosocial availability",
        "native_geography_level": "SA2; SA3; LGA; or service district uncertain",
        "required_join_geography": "documented geography required",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "depends on native geography",
        "weight_or_allocation_method": "document required",
        "suppression_or_missingness_rule": "suppression required",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "NDIS data does not capture full psychosocial support system.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Investigate before integration.",
    },
    {
        "source_id": "SRC011",
        "source_name": "PHIDU Social Health Atlas",
        "publisher": "PHIDU",
        "dataset_or_product_name": "Social Health Atlas",
        "source_url_or_access_path": "",
        "predictor_domain": "health; welfare; service context",
        "candidate_variables": "health status; disability; caring; welfare; service indicators",
        "reference_period": "closest to 2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check period and geography",
        "native_geography_level": "SA2-compatible; PHA; SA3; LGA; PHN",
        "required_join_geography": "documented geography required",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "do not treat PHA as native SA2 unless documented",
        "weight_or_allocation_method": "document required",
        "suppression_or_missingness_rule": "PHIDU suppression rules",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Population Health Area alignment must be documented.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Useful but geography-sensitive.",
    },
    {
        "source_id": "SRC012",
        "source_name": "AIHW Housing Assistance",
        "publisher": "AIHW",
        "dataset_or_product_name": "Housing Assistance in Australia",
        "source_url_or_access_path": "",
        "predictor_domain": "housing assistance",
        "candidate_variables": "social housing; CRA; housing assistance indicators",
        "reference_period": "closest to 2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check period and geography",
        "native_geography_level": "SA2; LGA; state uncertain",
        "required_join_geography": "documented geography required",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "depends on geography",
        "weight_or_allocation_method": "document required",
        "suppression_or_missingness_rule": "suppression required",
        "candidate_predictor_status": "retain_for_later_sensitivity_analysis",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Housing assistance, not full housing need.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Use only if geography and period defensible.",
    },
    {
        "source_id": "SRC013",
        "source_name": "AIHW Specialist Homelessness Services",
        "publisher": "AIHW",
        "dataset_or_product_name": "Specialist Homelessness Services Collection outputs",
        "source_url_or_access_path": "",
        "predictor_domain": "homelessness",
        "candidate_variables": "clients; requests; unmet need; outcomes",
        "reference_period": "closest to 2021-22",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check public geography",
        "native_geography_level": "LGA; SA3; PHN; or state uncertain",
        "required_join_geography": "documented geography required",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "depends on geography",
        "weight_or_allocation_method": "document required",
        "suppression_or_missingness_rule": "suppression required",
        "candidate_predictor_status": "retain_for_later_sensitivity_analysis",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "SHS service use, not total homelessness prevalence.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "May be hard to align nationally.",
    },
    {
        "source_id": "SRC014",
        "source_name": "Australian Early Development Census",
        "publisher": "AEDC",
        "dataset_or_product_name": "AEDC 2021 community data",
        "source_url_or_access_path": "",
        "predictor_domain": "child and family developmental context",
        "candidate_variables": "developmental vulnerability; social competence; emotional maturity",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned if geography suitable",
        "native_geography_level": "community geography uncertain",
        "required_join_geography": "documented geography required",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "depends on AEDC geography",
        "weight_or_allocation_method": "document required",
        "suppression_or_missingness_rule": "suppression required",
        "candidate_predictor_status": "retain_for_later_sensitivity_analysis",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "interpretation_limit": "Child-development context only, not direct population-wide mental-health determinant.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Optional domain.",
    },
    {
        "source_id": "SRC015",
        "source_name": "SA2 to SA3 correspondence",
        "publisher": "ABS",
        "dataset_or_product_name": "ASGS Edition 3 correspondences",
        "source_url_or_access_path": "",
        "predictor_domain": "geography bridge",
        "candidate_variables": "SA2 to SA3 bridge and weights",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2 and SA3",
        "required_join_geography": "SA3",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "official correspondence",
        "weight_or_allocation_method": "ABS weight if available",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_now",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "interpretation_limit": "Bridge infrastructure.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Required for AIHW SA3 joins.",
    },
    {
        "source_id": "SRC016",
        "source_name": "SA2 to PHN correspondence",
        "publisher": "ABS or Department of Health",
        "dataset_or_product_name": "ASGS/non-ABS structure correspondence",
        "source_url_or_access_path": "",
        "predictor_domain": "geography bridge",
        "candidate_variables": "SA2 to PHN bridge and weights",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "check available period",
        "native_geography_level": "SA2 and PHN",
        "required_join_geography": "PHN",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "official correspondence or documented allocation",
        "weight_or_allocation_method": "population or area weight where available",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "interpretation_limit": "Bridge infrastructure.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Required before PHN predictors.",
    },
    {
        "source_id": "SRC017",
        "source_name": "SA2 to LGA correspondence",
        "publisher": "ABS",
        "dataset_or_product_name": "ASGS Edition 3 correspondences",
        "source_url_or_access_path": "",
        "predictor_domain": "geography bridge",
        "candidate_variables": "SA2 to LGA bridge and weights",
        "reference_period": "2021",
        "desired_reference_period": "2021",
        "temporal_alignment_status": "aligned",
        "native_geography_level": "SA2 and LGA",
        "required_join_geography": "LGA",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "official correspondence",
        "weight_or_allocation_method": "ABS weight where available",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "interpretation_limit": "Bridge infrastructure.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Required before LGA predictors.",
    },
    {
        "source_id": "SRC018",
        "source_name": "SA2 to LHD correspondence",
        "publisher": "state health departments",
        "dataset_or_product_name": "state health geography correspondence",
        "source_url_or_access_path": "",
        "predictor_domain": "geography bridge",
        "candidate_variables": "SA2 to LHD or equivalent mapping",
        "reference_period": "closest available",
        "desired_reference_period": "2021-22",
        "temporal_alignment_status": "check state by state",
        "native_geography_level": "LHD or equivalent",
        "required_join_geography": "LHD",
        "bridge_or_correspondence_required": "yes",
        "proposed_join_method": "state-specific documented allocation",
        "weight_or_allocation_method": "population or area weight where available",
        "suppression_or_missingness_rule": "not applicable",
        "candidate_predictor_status": "integrate_after_geography_check",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "interpretation_limit": "Not nationally standard without checking.",
        "download_status": "not_started",
        "integration_status": "not_started",
        "validation_status": "not_started",
        "notes": "Do later.",
    },
]


def main() -> None:
    """Create the source acquisition register for the blank-slate build."""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(ROWS, columns=COLUMNS)

    if df["source_id"].duplicated().any():
        duplicates = df.loc[df["source_id"].duplicated(), "source_id"].tolist()
        raise ValueError(f"Duplicate source_id values found: {duplicates}")

    df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

    print(f"Created source acquisition register:")
    print(OUTPUT_PATH)
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")


if __name__ == "__main__":
    main()
