from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"D:\Good Measure\MentalWellbeingbyGeography")

OUTPUT_PATH = PROJECT_ROOT / "docs" / "source_registers" / "source_validation_register.csv"

COLUMNS = [
    "source_id",
    "source_name",
    "validation_priority",
    "official_source_found",
    "official_source_url",
    "public_download_available",
    "download_format",
    "reference_period_confirmed",
    "native_geography_confirmed",
    "geography_level",
    "sa2_2021_compatible",
    "sa3_2021_compatible",
    "phn_compatible",
    "lga_compatible",
    "lhd_compatible",
    "correspondence_required",
    "suppression_rules_found",
    "data_dictionary_found",
    "licence_or_usage_notes",
    "validation_status",
    "validated_by",
    "validation_date",
    "notes",
]

ROWS = [
    {
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "validation_priority": "foundation",
        "official_source_found": "yes",
        "official_source_url": "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/latest-release",
        "public_download_available": "yes",
        "download_format": "xlsx; csv; geopackage; shapefile depending product",
        "reference_period_confirmed": "2021",
        "native_geography_confirmed": "yes",
        "geography_level": "SA2",
        "sa2_2021_compatible": "yes",
        "sa3_2021_compatible": "yes via ASGS hierarchy",
        "phn_compatible": "requires separate correspondence",
        "lga_compatible": "requires separate correspondence",
        "lhd_compatible": "requires separate correspondence",
        "correspondence_required": "no for SA2 spine; yes for non-ASGS structures",
        "suppression_rules_found": "not applicable",
        "data_dictionary_found": "check downloaded file metadata",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "part_validated",
        "validated_by": "",
        "validation_date": "",
        "notes": "Foundation geography source. Confirm exact file to use before acquisition.",
    },
    {
        "source_id": "SRC002",
        "source_name": "NSMHW modelled mental-health prevalence",
        "validation_priority": "foundation",
        "official_source_found": "partial",
        "official_source_url": "https://www.abs.gov.au/statistics/health/mental-health/national-study-mental-health-and-wellbeing/latest-release",
        "public_download_available": "unknown for SA2 modelled estimates",
        "download_format": "to be confirmed",
        "reference_period_confirmed": "2020-2022",
        "native_geography_confirmed": "not yet confirmed for SA2 modelled estimates",
        "geography_level": "SA2 required; not yet confirmed",
        "sa2_2021_compatible": "to be confirmed",
        "sa3_2021_compatible": "not applicable",
        "phn_compatible": "not applicable",
        "lga_compatible": "not applicable",
        "lhd_compatible": "not applicable",
        "correspondence_required": "no if native SA2 2021; otherwise yes",
        "suppression_rules_found": "to be confirmed",
        "data_dictionary_found": "to be confirmed",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "requires_validation",
        "validated_by": "",
        "validation_date": "",
        "notes": "The general NSMHW survey release is validated. The SA2 modelled small-area estimate product still needs to be located and validated.",
    },
    {
        "source_id": "SRC003",
        "source_name": "Census 2021 SA2 predictors",
        "validation_priority": "foundation",
        "official_source_found": "yes",
        "official_source_url": "https://www.abs.gov.au/census/find-census-data/datapacks",
        "public_download_available": "yes",
        "download_format": "csv data packs; metadata",
        "reference_period_confirmed": "2021",
        "native_geography_confirmed": "yes if SA2 data pack selected",
        "geography_level": "SA2",
        "sa2_2021_compatible": "yes",
        "sa3_2021_compatible": "not required",
        "phn_compatible": "not required",
        "lga_compatible": "not required",
        "lhd_compatible": "not required",
        "correspondence_required": "no",
        "suppression_rules_found": "check Census data pack metadata",
        "data_dictionary_found": "check downloaded metadata",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "requires_file_level_validation",
        "validated_by": "",
        "validation_date": "",
        "notes": "Validate exact Census tables and column metadata before integration.",
    },
    {
        "source_id": "SRC004",
        "source_name": "SEIFA 2021",
        "validation_priority": "foundation",
        "official_source_found": "yes",
        "official_source_url": "https://www.abs.gov.au/statistics/people/people-and-communities/socio-economic-indexes-areas-seifa-australia/latest-release",
        "public_download_available": "yes",
        "download_format": "xlsx or csv depending release file",
        "reference_period_confirmed": "2021",
        "native_geography_confirmed": "yes if SA2 table selected",
        "geography_level": "SA2",
        "sa2_2021_compatible": "yes",
        "sa3_2021_compatible": "not required",
        "phn_compatible": "not required",
        "lga_compatible": "not required",
        "lhd_compatible": "not required",
        "correspondence_required": "no",
        "suppression_rules_found": "check SEIFA technical documentation",
        "data_dictionary_found": "check downloaded metadata",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "requires_file_level_validation",
        "validated_by": "",
        "validation_date": "",
        "notes": "Validate selected indexes, rankings, deciles and percentiles.",
    },
    {
        "source_id": "SRC005",
        "source_name": "ASGS Remoteness 2021",
        "validation_priority": "foundation",
        "official_source_found": "yes",
        "official_source_url": "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/latest-release",
        "public_download_available": "yes",
        "download_format": "allocation files; boundaries; correspondence files depending method",
        "reference_period_confirmed": "2021",
        "native_geography_confirmed": "check exact remoteness allocation file",
        "geography_level": "SA2 or lower-level allocation to Remoteness Area",
        "sa2_2021_compatible": "to be confirmed from allocation file",
        "sa3_2021_compatible": "not required",
        "phn_compatible": "not required",
        "lga_compatible": "not required",
        "lhd_compatible": "not required",
        "correspondence_required": "maybe",
        "suppression_rules_found": "not applicable",
        "data_dictionary_found": "check ASGS metadata",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "requires_file_level_validation",
        "validated_by": "",
        "validation_date": "",
        "notes": "Need to confirm whether SA2 can be assigned directly or via allocation from smaller geography.",
    },
    {
        "source_id": "SRC006",
        "source_name": "AIHW Regional Profiles mental-health service activity",
        "validation_priority": "stage_2",
        "official_source_found": "yes",
        "official_source_url": "https://www.aihw.gov.au/mental-health/monitoring/regional-profiles",
        "public_download_available": "to be confirmed",
        "download_format": "tool/table download to be confirmed",
        "reference_period_confirmed": "time series available; 2021-22 requires check",
        "native_geography_confirmed": "yes",
        "geography_level": "PHN and SA3",
        "sa2_2021_compatible": "requires SA2-to-SA3 join",
        "sa3_2021_compatible": "yes, but exact SA3 edition to confirm",
        "phn_compatible": "yes",
        "lga_compatible": "not native",
        "lhd_compatible": "not native",
        "correspondence_required": "yes for SA2 analysis",
        "suppression_rules_found": "to be confirmed",
        "data_dictionary_found": "to be confirmed",
        "licence_or_usage_notes": "check AIHW usage terms",
        "validation_status": "requires_file_level_validation",
        "validated_by": "",
        "validation_date": "",
        "notes": "Validated as PHN/SA3 regional service-activity source, but not yet as a downloaded 2021-22 analysis file.",
    },
    {
        "source_id": "SRC015",
        "source_name": "SA2 to SA3 correspondence",
        "validation_priority": "foundation",
        "official_source_found": "yes",
        "official_source_url": "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/correspondences",
        "public_download_available": "yes",
        "download_format": "csv",
        "reference_period_confirmed": "2021",
        "native_geography_confirmed": "yes",
        "geography_level": "SA2 to SA3",
        "sa2_2021_compatible": "yes",
        "sa3_2021_compatible": "yes",
        "phn_compatible": "not applicable",
        "lga_compatible": "not applicable",
        "lhd_compatible": "not applicable",
        "correspondence_required": "yes",
        "suppression_rules_found": "not applicable",
        "data_dictionary_found": "correspondence metadata available",
        "licence_or_usage_notes": "check ABS usage terms",
        "validation_status": "part_validated",
        "validated_by": "",
        "validation_date": "",
        "notes": "Confirm exact correspondence file name during acquisition.",
    },
]

def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(ROWS, columns=COLUMNS)

    if df["source_id"].duplicated().any():
        duplicates = df.loc[df["source_id"].duplicated(), "source_id"].tolist()
        raise ValueError(f"Duplicate source_id values found: {duplicates}")

    df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

    print(f"Created source validation register:")
    print(OUTPUT_PATH)
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")

if __name__ == "__main__":
    main()
