from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(r"D:\Good Measure\MentalWellbeingbyGeography")

OUTPUT_PATH = (
    PROJECT_ROOT
    / "docs"
    / "source_registers"
    / "variable_classification_register.csv"
)

COLUMNS = [
    "variable_name",
    "source_id",
    "source_name",
    "source_geography",
    "reference_period",
    "variable_label",
    "predictor_domain",
    "field_role",
    "model_eligibility",
    "preferred_transform",
    "denominator_variable",
    "missingness_rule",
    "suppression_rule",
    "outcome_overlap_risk",
    "target_leakage_risk",
    "collinearity_group",
    "interpretation_note",
    "review_status",
]

ROWS = [
    {
        "variable_name": "sa2_code_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "SA2 code, 2021 ASGS Edition 3",
        "predictor_domain": "geography",
        "field_role": "identifier",
        "model_eligibility": "exclude_from_models",
        "preferred_transform": "none",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "collinearity_group": "geography_identifier",
        "interpretation_note": "Primary row identifier. Not a predictor.",
        "review_status": "draft",
    },
    {
        "variable_name": "sa2_name_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "SA2 name, 2021 ASGS Edition 3",
        "predictor_domain": "geography",
        "field_role": "identifier",
        "model_eligibility": "exclude_from_models",
        "preferred_transform": "none",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "collinearity_group": "geography_identifier",
        "interpretation_note": "Descriptive geography label. Not a predictor.",
        "review_status": "draft",
    },
    {
        "variable_name": "sa3_code_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "SA3 code, 2021 ASGS Edition 3",
        "predictor_domain": "geography",
        "field_role": "cluster_key",
        "model_eligibility": "use_for_grouped_splitting_and_multilevel_structure",
        "preferred_transform": "categorical_grouping_key",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "medium",
        "collinearity_group": "geography_cluster",
        "interpretation_note": "Required cluster key because SA3-level predictors will be repeated onto SA2 rows.",
        "review_status": "draft",
    },
    {
        "variable_name": "sa3_name_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "SA3 name, 2021 ASGS Edition 3",
        "predictor_domain": "geography",
        "field_role": "identifier",
        "model_eligibility": "exclude_from_models",
        "preferred_transform": "none",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "low",
        "target_leakage_risk": "low",
        "collinearity_group": "geography_identifier",
        "interpretation_note": "Descriptive cluster label. Not a predictor.",
        "review_status": "draft",
    },
    {
        "variable_name": "state_code_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "State or territory code",
        "predictor_domain": "jurisdictional context",
        "field_role": "cluster_key",
        "model_eligibility": "use_as_fixed_effect_or_grouping_context_if_required",
        "preferred_transform": "categorical",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "collinearity_group": "jurisdiction",
        "interpretation_note": "Jurisdictional context. Use carefully because it may absorb state-level policy and measurement differences.",
        "review_status": "draft",
    },
    {
        "variable_name": "state_name_2021",
        "source_id": "SRC001",
        "source_name": "SA2 2021 geography spine",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "State or territory name",
        "predictor_domain": "jurisdictional context",
        "field_role": "identifier",
        "model_eligibility": "exclude_from_models_unless_recoded",
        "preferred_transform": "categorical_if_used",
        "denominator_variable": "",
        "missingness_rule": "must_not_be_missing",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "collinearity_group": "jurisdiction",
        "interpretation_note": "Descriptive jurisdiction label.",
        "review_status": "draft",
    },
    {
        "variable_name": "nsmhw_any_12m_disorder_estimated_pct",
        "source_id": "SRC002",
        "source_name": "NSMHW modelled mental-health prevalence",
        "source_geography": "SA2",
        "reference_period": "2020-2022",
        "variable_label": "Modelled estimated percentage with any 12-month mental disorder",
        "predictor_domain": "outcome",
        "field_role": "outcome",
        "model_eligibility": "primary_outcome",
        "preferred_transform": "continuous_untransformed_then_check_distribution",
        "denominator_variable": "",
        "missingness_rule": "do_not_impute",
        "suppression_rule": "follow_abs_reliability_and_suppression_flags",
        "outcome_overlap_risk": "not_applicable",
        "target_leakage_risk": "not_applicable",
        "collinearity_group": "outcome",
        "interpretation_note": "Primary dependent variable. ABS modelled small-area estimate, not observed diagnosis or service-contact count.",
        "review_status": "draft",
    },
    {
        "variable_name": "nsmhw_severe_12m_disorder_estimated_pct",
        "source_id": "SRC002",
        "source_name": "NSMHW modelled mental-health prevalence",
        "source_geography": "SA2",
        "reference_period": "2020-2022",
        "variable_label": "Modelled estimated percentage with severe 12-month mental disorder",
        "predictor_domain": "outcome",
        "field_role": "outcome",
        "model_eligibility": "secondary_sensitivity_outcome",
        "preferred_transform": "continuous_untransformed_then_check_distribution",
        "denominator_variable": "",
        "missingness_rule": "do_not_impute",
        "suppression_rule": "follow_abs_reliability_and_suppression_flags",
        "outcome_overlap_risk": "not_applicable",
        "target_leakage_risk": "not_applicable",
        "collinearity_group": "outcome",
        "interpretation_note": "Secondary dependent variable. ABS modelled small-area estimate, not observed diagnosis or service-contact count.",
        "review_status": "draft",
    },
    {
        "variable_name": "nsmhw_outcome_reliability_flag",
        "source_id": "SRC002",
        "source_name": "NSMHW modelled mental-health prevalence",
        "source_geography": "SA2",
        "reference_period": "2020-2022",
        "variable_label": "Outcome reliability or quality flag",
        "predictor_domain": "outcome quality",
        "field_role": "quality_or_reliability_context",
        "model_eligibility": "exclude_from_predictor_set_use_for_sensitivity",
        "preferred_transform": "categorical",
        "denominator_variable": "",
        "missingness_rule": "must_review",
        "suppression_rule": "follow_abs_rules",
        "outcome_overlap_risk": "not_applicable",
        "target_leakage_risk": "high",
        "collinearity_group": "outcome_quality",
        "interpretation_note": "Use for inclusion, reliability review and sensitivity analysis. Do not use as a predictor.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
    {
        "variable_name": "seifa_irsd_score",
        "source_id": "SRC004",
        "source_name": "SEIFA 2021",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "Index of Relative Socio-economic Disadvantage score",
        "predictor_domain": "socioeconomic disadvantage",
        "field_role": "candidate_predictor",
        "model_eligibility": "eligible_after_overlap_review",
        "preferred_transform": "standardise_within_training_fold",
        "denominator_variable": "",
        "missingness_rule": "missingness_indicator_plus_training_fold_imputation_if_numeric",
        "suppression_rule": "follow_abs_seifa_rules",
        "outcome_overlap_risk": "high",
        "target_leakage_risk": "medium",
        "collinearity_group": "seifa_socioeconomic_disadvantage",
        "interpretation_note": "Composite socioeconomic index. Likely overlaps with Census predictors and may overlap with ABS modelled outcome inputs.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
    {
        "variable_name": "seifa_irsd_decile",
        "source_id": "SRC004",
        "source_name": "SEIFA 2021",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "Index of Relative Socio-economic Disadvantage decile",
        "predictor_domain": "socioeconomic disadvantage",
        "field_role": "candidate_predictor",
        "model_eligibility": "eligible_after_overlap_review_but_do_not_use_with_score_in_same_interpretable_model_without_reason",
        "preferred_transform": "ordinal_or_categorical_sensitivity",
        "denominator_variable": "",
        "missingness_rule": "explicit_missing_category_if_categorical",
        "suppression_rule": "follow_abs_seifa_rules",
        "outcome_overlap_risk": "high",
        "target_leakage_risk": "medium",
        "collinearity_group": "seifa_socioeconomic_disadvantage",
        "interpretation_note": "Derived from SEIFA score. Avoid duplicating score, rank and decile in the same interpretable regression model.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
    {
        "variable_name": "remoteness_area_2021",
        "source_id": "SRC005",
        "source_name": "ASGS Remoteness 2021",
        "source_geography": "SA2",
        "reference_period": "2021",
        "variable_label": "Remoteness Area category",
        "predictor_domain": "remoteness",
        "field_role": "candidate_predictor",
        "model_eligibility": "eligible_after_geography_validation",
        "preferred_transform": "categorical_or_ordered_sensitivity",
        "denominator_variable": "",
        "missingness_rule": "explicit_missing_category_if_categorical",
        "suppression_rule": "not_applicable",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "low",
        "collinearity_group": "remoteness",
        "interpretation_note": "Area remoteness context. Do not interpret as causal effect.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
    {
        "variable_name": "aihw_mh_medicare_patients_rate",
        "source_id": "SRC006",
        "source_name": "AIHW Regional Profiles mental-health service activity",
        "source_geography": "SA3",
        "reference_period": "2021-22",
        "variable_label": "Medicare mental-health patients rate",
        "predictor_domain": "mental health service activity",
        "field_role": "candidate_predictor",
        "model_eligibility": "eligible_after_sa3_join_validation",
        "preferred_transform": "standardise_within_training_fold",
        "denominator_variable": "",
        "missingness_rule": "missingness_indicator_plus_training_fold_imputation_if_numeric",
        "suppression_rule": "suppressed_or_unpublished_values_require_explicit_handling",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "collinearity_group": "aihw_medicare_service_activity",
        "interpretation_note": "SA3-level service-activity indicator repeated onto SA2 rows. Not a direct SA2 access or adequacy measure.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
    {
        "variable_name": "aihw_mh_ed_presentations_rate",
        "source_id": "SRC006",
        "source_name": "AIHW Regional Profiles mental-health service activity",
        "source_geography": "SA3",
        "reference_period": "2021-22",
        "variable_label": "Mental health-related emergency department presentations rate",
        "predictor_domain": "mental health service activity",
        "field_role": "candidate_predictor",
        "model_eligibility": "eligible_after_sa3_join_validation",
        "preferred_transform": "standardise_within_training_fold",
        "denominator_variable": "",
        "missingness_rule": "missingness_indicator_plus_training_fold_imputation_if_numeric",
        "suppression_rule": "suppressed_or_unpublished_values_require_explicit_handling",
        "outcome_overlap_risk": "medium",
        "target_leakage_risk": "medium",
        "collinearity_group": "aihw_ed_service_activity",
        "interpretation_note": "SA3-level service-activity indicator repeated onto SA2 rows. Not a direct SA2 access or adequacy measure.",
        "review_status": "placeholder_pending_actual_source_columns",
    },
]


def main() -> None:
    """Create the variable classification register."""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    df = pd.DataFrame(ROWS, columns=COLUMNS)

    if df["variable_name"].duplicated().any():
        duplicates = df.loc[df["variable_name"].duplicated(), "variable_name"].tolist()
        raise ValueError(f"Duplicate variable_name values found: {duplicates}")

    allowed_field_roles = {
        "outcome",
        "candidate_predictor",
        "identifier",
        "cluster_key",
        "weight_or_denominator_candidate",
        "quality_or_reliability_context",
        "availability_or_processing_audit",
        "target_leakage_exclusion",
        "manual_review_required",
    }

    invalid_roles = sorted(set(df["field_role"]) - allowed_field_roles)
    if invalid_roles:
        raise ValueError(f"Invalid field_role values found: {invalid_roles}")

    df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

    print("Created variable classification register:")
    print(OUTPUT_PATH)
    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")


if __name__ == "__main__":
    main()
